;; The first four lines of this file were added by Dracula.
;; They tell DrScheme that this is a Dracula Modular ACL2 program.
;; Leave these lines unchanged so that DrScheme can properly load this file.
#reader(planet "reader.rkt" ("cce" "dracula.plt") "modular" "lang")
(interface IQRCode
  (sig QRCode ())
  (sig QRCode:getMode (code))
  (sig QRCode:getECLevel (code))
  (sig QRCode:getVersion (code))
  (sig QRCode:getMatrixWidth (code))
  (sig QRCode:getMaskPattern (code))
  (sig QRCode:getNumTotalBytes (code))
  (sig QRCode:getNumDataBytes (code))
  (sig QRCode:getNumECBytes (code))
  (sig QRCode:getNumRSBlocks (code))
  (sig QRCode:getMatrix (code))
  (sig QRCode:at (code x y))
  (sig QRCode:isValidMaskPattern (maskPattern))
  (sig QRCode:isValid (code))
  (sig QRCode:setMode (code value))
  (sig QRCode:setECLevel (code value))
  (sig QRCode:setVersion (code value))
  (sig QRCode:setMatrixWidth (code value))
  (sig QRCode:setMaskPattern (code value))
  (sig QRCode:setNumTotalBytes (code value))
  (sig QRCode:setNumDataBytes (code value))
  (sig QRCode:setNumECBytes (code value))
  (sig QRCode:setNumRSBlocks (code value))
  (sig QRCode:setMatrix (code value))
  (sig ErrorCorrectionLevel$3 (ordinal bits name))
  (sig ErrorCorrectionLevel:ordinal (ecl))
  (sig ErrorCorrectionLevel:getBits (ecl))
  (sig ErrorCorrectionLevel:getName (ecl))
  (sig ErrorCorrectionLevel:forBits (bits))
  (sig FormatInformation$1 (formatInfo))
  (sig FormatInformation:numBitsDiffering (a b))
  (sig FormatInformation:doDecodeFormatInformation (maskedFormatInfo1 maskedFormatInfo2))
  (sig FormatInformation:decodeFormatInformation (maskedFormatInfo1 maskedFormatInfo2))
  (sig FormatInformation:getErrorCorrectionLevel (fi))
  (sig FormatInformation:getDataMask (fi))
  (sig ECB:getCount (ecb))
  (sig ECB:getDataCodewords (ecb))
  (sig ECBlocks:getECCodewordsPerBlock (ecBlocks) )
  (sig ECBlocks:getNumBlocks (ecBlocks))
  (sig ECBlocks:getTotalECCodewords (ecBlocks))
  (sig ECBlocks:getECBlocks (ecBlocks))
  (sig Version:getVersionNumber (version))
  (sig Version:getAlignmentPatternCenters (version))
  (sig Version:getTotalCodewords (version))
  (sig Version:getDimensionForVersion (version))
  (sig Version:getECBlocksForLevel (version ecLevel))
  (sig Version:getVersionForNumber (versionNumber))
  (sig Version:getProvisionalVersionForDimension (dimension))
  (sig Version:decodeVersionInformation (versionBits))
  (sig Version:buildFunctionPattern (version))
  (sig Mode (characterCountBitsForVersions bits name))
  (sig Mode:forBits (bits))
  (sig Mode:getBits(mode))
  (sig Mode:getName (mode))
  (sig Mode:getCharacterCountBits (mode version)))